version: "3.8"

services:
  socket:
    container_name: socket
    image: socket
    build:
      context: "../backend"
      dockerfile: socket.dockerfile
    ports:
      - "5000:5000"

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  chat-app:
    container_name: chat-app
    image: frontend
    build:
      context: .
      dockerfile: frontend.dockerfile

    ports:
      - 3000:3000
    volumes:
      - .:/chat-app
      - /chat-app/node_modules
    depends_on:
      - db
      - socket
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    restart: always

volumes:
  db-data:
