# FROM node:18-alpine


# WORKDIR /chat-app


# COPY package*.json ./

# RUN npm ci
# COPY prisma ./prisma/

# RUN npm install

# RUN npx prisma generate

# COPY . .

# RUN npm run build

# COPY .next ./.next.

# CMD ["npm", "run", "dev"]